### ISSUE TITLE
打开库失败了，编译没有问题

### ISSUE THREAD

**Issue by believerchen** [qingkouwei/oarplayer#1]
!!!!!!!! failed to load library

static oar_dl_context *create_dl_context()
{
    oar_dl_context *dl_context = (oar_dl_context *)malloc(sizeof(oar_dl_context));
    dl_context->libHandler = dlopen("./libmediacodec-lib.so", RTLD_NOW);
    if (!dl_context->libHandler) {
        LOGE("!!!!!!!! failed to load library");
        return NULL;
    }

    dl_context->create_native_mediacodec = dlsym(dl_context->libHandler, "oar_create_native_mediacodec");
    dl_context->native_mediacodec_flush = dlsym(dl_context->libHandler, "oar_native_mediacodec_flush");
    dl_context->native_mediacodec_receive_frame = dlsym(dl_context->libHandler, "oar_native_mediacodec_receive_frame");
    dl_context->native_mediacodec_release_buffer = dlsym(dl_context->libHandler, "oar_native_mediacodec_release_buffer");
    dl_context->native_mediacodec_release_context = dlsym(dl_context->libHandler, "oar_native_mediacodec_release_context");
    dl_context->native_mediacodec_send_packet = dlsym(dl_context->libHandler, "oar_native_mediacodec_send_packet");
    dl_context->native_mediacodec_start = dlsym(dl_context->libHandler, "oar_native_mediacodec_start");
    dl_context->native_mediacodec_stop = dlsym(dl_context->libHandler, "oar_native_mediacodec_stop");
    return dl_context;

**Comment by jasonchuang** [comment]
同上, 打包的 apk 資料夾內的內容:
arm64-v8a: `liboarp-lib.so` and armeabi-v7a: `libmediacodec-lib.so`
還是可以請大大出一包驗證成功的 apk in release tab 🙇

**Comment by qingkouwei** [comment]
可以提供具体的信息吗?手机系统之类的

**Comment by qingkouwei** [comment]
路径问题,已修复
